

spring:
  graphql:
    graphiql:
      enabled: true
      # graphiql을 true를 설정해 주면 localhost:8080/h2-console과 같이 localhost:8080/graphiql 통해
      # graphql 쿼리를 테스트가 가능합니다.
      printer:
        enabled: true
        # 이 설정 시 jpa에 show-sql 같이 graphql 쿼리를 출력해 줍니다.


  #TODO: 프로필 추가
  datasource:
    url: jdbc:mysql://localhost:3306/framework?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  #TODO: logging decorator


